<CityMapScreen>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: (0.05, 0.05, 0.05, 1) # Dark background
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            id: status_full
            text: "Initializing City Map..."
            color: (0.5, 0.5, 0.5, 1)
            text_size: self.size
            halign: 'center'
            valign: 'middle'
